In [1]:
from sympy import *
import numpy as np

### Задача 1.


Вычислите значения выражений.

In [12]:
a = np.array([2, 5, 0, 6, 8, 10, 6, 7, 5, 7], dtype=np.int32)
b = np.array([8, 6, 7, 9, 6, 6, 2, 3, 2, 3], dtype=np.int32)
np.dot(3*a, 2*b)

1632

In [11]:
a = np.array([9, 6, 7, 7, 0, 1, 6, 8, 1, 2], dtype=np.int32)
b = np.array([0, 2, 2, 6, 7, 8, 8, 3, 1, 8], dtype=np.int32)
np.dot(6*a, 5*b)

4950

In [13]:
a = np.array([2, 5, 0, 6, 8, 10, 6, 7, 5, 7], dtype=np.int32)
b = np.array([8, 6, 7, 9, 6, 6, 2, 3, 2, 3], dtype=np.int32)
np.dot(a, b)

272

In [14]:
a = np.array([9, 6, 7, 7, 0, 1, 6, 8, 1, 2], dtype=np.int32)
b = np.array([0, 2, 2, 6, 7, 8, 8, 3, 1, 8], dtype=np.int32)
np.dot(a, b)

165

### Задача 2.
Для следующих заданий сделайте в Python функцию, реализующую транспонирование матрицы произвольной размерности, пользуясь данным в модуле определением. Функция должна принимать и возвращать либо numpy.array, либо двумерный список (list).

In [2]:
def transpose(x):
    x_tr = np.zeros(shape=(x.shape[1], x.shape[0]), dtype=np.int32)
    for i in range(0, x.shape[0]):
        for j in range(0, x.shape[1]):
            x_tr[j][i] = x[i][j]
    return x_tr
    

In [3]:
a = np.array([[2, 1, 7, 4],
              [5, 6, 7, 3],
              [9, 8, 2, 12],
              [11, 14, 15, 15]])
print(a)
print(transpose(a))

[[ 2  1  7  4]
 [ 5  6  7  3]
 [ 9  8  2 12]
 [11 14 15 15]]
[[ 2  5  9 11]
 [ 1  6  8 14]
 [ 7  7  2 15]
 [ 4  3 12 15]]


In [4]:
b = np.array([[3, 7, 8, 3, 6],
              [2, 5, 9, 4, 13]])
print(b)
print(transpose(b))

[[ 3  7  8  3  6]
 [ 2  5  9  4 13]]
[[ 3  2]
 [ 7  5]
 [ 8  9]
 [ 3  4]
 [ 6 13]]
