In [1]:
from sympy import *
import numpy as np

### Задача 1.


Вычислите значения выражений.

In [2]:
a = np.array([2, 5, 0, 6, 8, 10, 6, 7, 5, 7], dtype=np.int32)
b = np.array([8, 6, 7, 9, 6, 6, 2, 3, 2, 3], dtype=np.int32)
np.dot(3*a, 2*b)

1632

In [3]:
a = np.array([9, 6, 7, 7, 0, 1, 6, 8, 1, 2], dtype=np.int32)
b = np.array([0, 2, 2, 6, 7, 8, 8, 3, 1, 8], dtype=np.int32)
np.dot(6*a, 5*b)

4950

In [4]:
a = np.array([2, 5, 0, 6, 8, 10, 6, 7, 5, 7], dtype=np.int32)
b = np.array([8, 6, 7, 9, 6, 6, 2, 3, 2, 3], dtype=np.int32)
np.dot(a, b)

272

In [5]:
a = np.array([9, 6, 7, 7, 0, 1, 6, 8, 1, 2], dtype=np.int32)
b = np.array([0, 2, 2, 6, 7, 8, 8, 3, 1, 8], dtype=np.int32)
np.dot(a, b)

165

### Задача 2.
Для следующих заданий сделайте в Python функцию, реализующую транспонирование матрицы произвольной размерности, пользуясь данным в модуле определением. Функция должна принимать и возвращать либо numpy.array, либо двумерный список (list).

In [6]:
def transpose(x):
    x_tr = np.zeros(shape=(x.shape[1], x.shape[0]), dtype=np.int32)
    for i in range(0, x.shape[0]):
        for j in range(0, x.shape[1]):
            x_tr[j][i] = x[i][j]
    return x_tr
    

In [7]:
a = np.array([[2, 1, 7, 4],
              [5, 6, 7, 3],
              [9, 8, 2, 12],
              [11, 14, 15, 15]])
print(a)
print(transpose(a))

[[ 2  1  7  4]
 [ 5  6  7  3]
 [ 9  8  2 12]
 [11 14 15 15]]
[[ 2  5  9 11]
 [ 1  6  8 14]
 [ 7  7  2 15]
 [ 4  3 12 15]]


In [8]:
b = np.array([[3, 7, 8, 3, 6],
              [2, 5, 9, 4, 13]])
print(b)
print(transpose(b))

[[ 3  7  8  3  6]
 [ 2  5  9  4 13]]
[[ 3  2]
 [ 7  5]
 [ 8  9]
 [ 3  4]
 [ 6 13]]


### Задача 3.


Завершите начатый в последнем уроке градиентный спуск. Вы можете решать эту задачу с помощью SymPy или вручную. Двигайтесь из точки в точку в направлении антиградиента, размер шага оставьте равным 0.01. Обратите внимание, что в каждой новой точке антиградиент будет разным. Добейтесь величины MSE меньше 6,36. Сколько шагов градиентного спуска вам потребовалось для этого?

In [9]:
a1, a2 = symbols('a1, a2')

In [10]:
MSE = 1/4 * ((a1*1 + a2*2 - 5)**2 + \
             (a1*5 + a2*3 - 6)**2 + \
             (a1*2 + a2*4 - 10)**2 + \
             (a1*3 + a2*7 - 8)**2)
MSE

0.25*(a1 + 2*a2 - 5)**2 + 0.25*(2*a1 + 4*a2 - 10)**2 + 0.25*(3*a1 + 7*a2 - 8)**2 + 0.25*(5*a1 + 3*a2 - 6)**2

In [11]:
diff(MSE, a1)

19.5*a1 + 23.0*a2 - 39.5

In [12]:
diff(MSE, a2)

23.0*a1 + 39.0*a2 - 62.0

In [34]:
step = 0.01

In [47]:
# Градиентный спуск до значения MSE < 6.36
step = 0.01
point = np.array([0, 0])
counter = 1

while MSE.subs({a1: point[0], a2: point[1]}) >= 6.36:
    print('Итерация: ', counter)
    print('Точка: ', point)
    print('MSE: ', MSE.subs({a1: point[0], a2: point[1]}))
    grad = np.array([diff(MSE, a1).subs({a1: point[0], a2: point[1]}),
                     diff(MSE, a2).subs({a1: point[0], a2: point[1]})])
    print('Градиент: ', grad)
    new_point = point - step * grad
    counter += 1
    print('-----------------------------------------------')
    point = new_point

print('Итерация: ', counter)
print('Точка: ', point)
print('MSE: ', MSE.subs({a1: point[0], a2: point[1]}))
print('Градиент: ', grad)

Итерация:  1
Точка:  [0 0]
MSE:  56.2500000000000
Градиент:  [-39.5000000000000 -62.0000000000000]
-----------------------------------------------
Итерация:  2
Точка:  [0.395000000000000 0.620000000000000]
MSE:  16.8572437500000
Градиент:  [-17.5375000000000 -28.7350000000000]
-----------------------------------------------
Итерация:  3
Точка:  [0.570375000000000 0.907350000000000]
MSE:  8.59365482859375
Градиент:  [-7.50863750000000 -13.4947250000000]
-----------------------------------------------
Итерация:  4
Точка:  [0.645461375000000 1.04229725000000]
MSE:  6.85191449679269
Градиент:  [-2.94066643750000 -6.50479562500000]
-----------------------------------------------
Итерация:  5
Точка:  [0.674868039375000 1.10734520625000]
MSE:  6.47725148826285
Градиент:  [-0.871133488437501 -3.29157205062501]
-----------------------------------------------
Итерация:  6
Точка:  [0.683579374259375 1.14026092675625]
MSE:  6.38978037646670
Градиент:  [0.0557991134515632 -1.80749824854063]
-------