In [1]:
from sympy import *
import numpy as np

### Задача 1.


Вычислите значения выражений.

In [2]:
a = np.array([2, 5, 0, 6, 8, 10, 6, 7, 5, 7], dtype=np.int32)
b = np.array([8, 6, 7, 9, 6, 6, 2, 3, 2, 3], dtype=np.int32)
np.dot(3*a, 2*b)

1632

In [3]:
a = np.array([9, 6, 7, 7, 0, 1, 6, 8, 1, 2], dtype=np.int32)
b = np.array([0, 2, 2, 6, 7, 8, 8, 3, 1, 8], dtype=np.int32)
np.dot(6*a, 5*b)

4950

In [4]:
a = np.array([2, 5, 0, 6, 8, 10, 6, 7, 5, 7], dtype=np.int32)
b = np.array([8, 6, 7, 9, 6, 6, 2, 3, 2, 3], dtype=np.int32)
np.dot(a, b)

272

In [5]:
a = np.array([9, 6, 7, 7, 0, 1, 6, 8, 1, 2], dtype=np.int32)
b = np.array([0, 2, 2, 6, 7, 8, 8, 3, 1, 8], dtype=np.int32)
np.dot(a, b)

165

### Задача 2.
Для следующих заданий сделайте в Python функцию, реализующую транспонирование матрицы произвольной размерности, пользуясь данным в модуле определением. Функция должна принимать и возвращать либо numpy.array, либо двумерный список (list).

In [6]:
def transpose(x):
    x_tr = np.zeros(shape=(x.shape[1], x.shape[0]), dtype=np.int32)
    for i in range(0, x.shape[0]):
        for j in range(0, x.shape[1]):
            x_tr[j][i] = x[i][j]
    return x_tr
    

In [7]:
a = np.array([[2, 1, 7, 4],
              [5, 6, 7, 3],
              [9, 8, 2, 12],
              [11, 14, 15, 15]])
print(a)
print(transpose(a))

[[ 2  1  7  4]
 [ 5  6  7  3]
 [ 9  8  2 12]
 [11 14 15 15]]
[[ 2  5  9 11]
 [ 1  6  8 14]
 [ 7  7  2 15]
 [ 4  3 12 15]]


In [8]:
b = np.array([[3, 7, 8, 3, 6],
              [2, 5, 9, 4, 13]])
print(b)
print(transpose(b))

[[ 3  7  8  3  6]
 [ 2  5  9  4 13]]
[[ 3  2]
 [ 7  5]
 [ 8  9]
 [ 3  4]
 [ 6 13]]


### Задача 3.


Завершите начатый в последнем уроке градиентный спуск. Вы можете решать эту задачу с помощью SymPy или вручную. Двигайтесь из точки в точку в направлении антиградиента, размер шага оставьте равным 0.01. Обратите внимание, что в каждой новой точке антиградиент будет разным. Добейтесь величины MSE меньше 6,36. Сколько шагов градиентного спуска вам потребовалось для этого?

In [9]:
a2, a1 = symbols('a2, a1')

In [10]:
MSE = 1/4 * ((a1*1 + a2*2 - 5)**2 + \
             (a1*5 + a2*3 - 6)**2 + \
             (a1*2 + a2*4 - 10)**2 + \
             (a1*3 + a2*7 - 8)**2)
MSE

0.25*(a1 + 2*a2 - 5)**2 + 0.25*(2*a1 + 4*a2 - 10)**2 + 0.25*(3*a1 + 7*a2 - 8)**2 + 0.25*(5*a1 + 3*a2 - 6)**2

In [11]:
diff(MSE, a1)

19.5*a1 + 23.0*a2 - 39.5

In [12]:
diff(MSE, a2)

23.0*a1 + 39.0*a2 - 62.0

In [13]:
MSE.subs({a1: 0, a2: 0})

56.2500000000000

In [14]:
grad0 = np.array([diff(MSE, a1).subs({a1: 0, a2: 0}),
                  diff(MSE, a2).subs({a1: 0, a2: 0})])
grad0

array([-39.5000000000000, -62.0000000000000], dtype=object)

In [15]:
MSE.subs({a1: 0.395, a2: 0.62})

16.8572437500000

In [16]:
grad1 = np.array([diff(MSE, a1).subs({a1: 0.395, a2: 0.62}),
                  diff(MSE, a2).subs({a1: 0.395, a2: 0.62})])
grad1

array([-17.5375000000000, -28.7350000000000], dtype=object)

In [17]:
MSE.subs({a1: 0.395+0.175, a2: 0.62+0.287})

8.60120050000000

In [18]:
grad2 = np.array([diff(MSE, a1).subs({a1: 0.395+0.175, a2: 0.62+0.287}),
                  diff(MSE, a2).subs({a1: 0.395+0.175, a2: 0.62+0.287})])
grad2

array([-7.52400000000000, -13.5170000000000], dtype=object)

In [19]:
MSE.subs({a1: 0.395+0.175+0.075, a2: 0.62+0.287+0.135})

6.85521175000000

In [20]:
grad3 = np.array([diff(MSE, a1).subs({a1: 0.395+0.175+0.075, a2: 0.62+0.287+0.135}),
                  diff(MSE, a2).subs({a1: 0.395+0.175+0.075, a2: 0.62+0.287+0.135})])
grad3

array([-2.95650000000000, -6.52700000000000], dtype=object)

In [21]:
MSE.subs({a1: 0.395+0.175+0.075+0.03, a2: 0.62+0.287+0.135+0.065})

6.47827425000000

In [22]:
grad4 = np.array([diff(MSE, a1).subs({a1: 0.395+0.175+0.075+0.03, a2: 0.62+0.287+0.135+0.065}),
                  diff(MSE, a2).subs({a1: 0.395+0.175+0.075+0.03, a2: 0.62+0.287+0.135+0.065})])
grad4

array([-0.876500000000000, -3.30200000000000], dtype=object)

In [23]:
MSE.subs({a1: 0.395+0.175+0.075+0.03+0.0087, a2: 0.62+0.287+0.135+0.065+0.033})

6.39025947750000

In [25]:
grad5 = np.array([diff(MSE, a1).subs({a1: 0.395+0.175+0.075+0.03+0.0087, a2: 0.62+0.287+0.135+0.065+0.033}),
                  diff(MSE, a2).subs({a1: 0.395+0.175+0.075+0.03+0.0087, a2: 0.62+0.287+0.135+0.065+0.033})])
grad5

array([0.0521500000000010, -1.81490000000001], dtype=object)

In [28]:
MSE.subs({a1: 0.395+0.175+0.075+0.03+0.0087-0.0005, a2: 0.62+0.287+0.135+0.065+0.033+0.018})

6.36367864000000

In [29]:
grad6 = np.array([diff(MSE, a1).subs({a1: 0.395+0.175+0.075+0.03+0.0087-0.0005, a2: 0.62+0.287+0.135+0.065+0.033+0.018}),
                  diff(MSE, a2).subs({a1: 0.395+0.175+0.075+0.03+0.0087-0.0005, a2: 0.62+0.287+0.135+0.065+0.033+0.018})])
grad6

array([0.456399999999999, -1.12440000000000], dtype=object)

In [30]:
MSE.subs({a1: 0.395+0.175+0.075+0.03+0.0087-0.0005-0.005, a2: 0.62+0.287+0.135+0.065+0.033+0.018+0.01})

6.35119639000000

In [31]:
grad7 = np.array([diff(MSE, a1).subs({a1: 0.395+0.175+0.075+0.03+0.0087-0.0005-0.005,
                                      a2: 0.62+0.287+0.135+0.065+0.033+0.018+0.01}),
                  diff(MSE, a2).subs({a1: 0.395+0.175+0.075+0.03+0.0087-0.0005-0.005,
                                      a2: 0.62+0.287+0.135+0.065+0.033+0.018+0.01})])
grad7

array([0.588900000000002, -0.849399999999996], dtype=object)

In [32]:
MSE.subs({a1: 0.395+0.175+0.075+0.03+0.0087-0.0005-0.005-0.006,
          a2: 0.62+0.287+0.135+0.065+0.033+0.018+0.01+0.008})

6.34136279000000

In [33]:
grad8 = np.array([diff(MSE, a1).subs({a1: 0.395+0.175+0.075+0.03+0.0087-0.0005-0.005-0.006,
                                      a2: 0.62+0.287+0.135+0.065+0.033+0.018+0.01+0.008}),
                  diff(MSE, a2).subs({a1: 0.395+0.175+0.075+0.03+0.0087-0.0005-0.005-0.006,
                                      a2: 0.62+0.287+0.135+0.065+0.033+0.018+0.01+0.008})])
grad8

array([0.655899999999999, -0.675400000000003], dtype=object)

In [34]:
MSE.subs({a1: 0.395+0.175+0.075+0.03+0.0087-0.0005-0.005-0.006-0.007,
          a2: 0.62+0.287+0.135+0.065+0.033+0.018+0.01+0.008+0.007})

6.33234994000000