In [46]:
import numpy as np

def convolution(input_arr: np.array, convolution: np.array):
  assert convolution.shape == (3, 3)
  result = np.zeros((input_arr.shape[0], input_arr.shape[1]))
  for i in range(1, input_arr.shape[0]-1):
      for j in range(1, input_arr.shape[1]-1):
          result[i][j] = np.sum(np.multiply(input_arr[i-1:i+2, j-1:j+2], convolution))
  return result[1:-1, 1:-1]

In [47]:
A = np.array([[3, 3, 2, 1, 0],
              [0, 0, 1, 3, 1],
              [3, 1, 2, 2, 3],
              [2, 0, 0, 2, 2],
              [2, 0, 0, 0, 1]])
in_matrix = np.array([[0, 1, 2],
                      [2, 2, 0],
                      [0, 1, 2]])

print(A, "\n", convolution(A, in_matrix))

[[3 3 2 1 0]
 [0 0 1 3 1]
 [3 1 2 2 3]
 [2 0 0 2 2]
 [2 0 0 0 1]] 
 [[12. 12. 17.]
 [10. 17. 19.]
 [ 9.  6. 14.]]
